application: zoumafrikapapasax
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- django_wsgi: on
- appstats: on

libraries:
- name: django
  version: 1.5

- name: lxml
  version: latest

- name: ssl
  version: latest

env_variables:
    DJANGO_SETTINGS_MODULE: 'zoumapp.settings'

handlers:
- url: /static/admin
  static_dir: static/admin
  expiration: '0'

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /static/
  static_dir: static/
  expiration: '0'

- url: /.*
  script: zoumapp.wsgi.application

